services:
  neo4j:
    image: neo4j:5.14-community
    container_name: up-election-neo4j
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/guru@9114
      - NEO4J_server_memory_pagecache_size=512M
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./neo4j_data/data:/var/lib/neo4j/data
      - ./neo4j_data/logs:/var/lib/neo4j/logs
      - ./neo4j_data/import:/var/lib/neo4j/import
      - ./neo4j_data/plugins:/var/lib/neo4j/plugins
